-- Generated automatically from CSV
begin;

insert into public.volunteers (
  reg_number, reg_type, entry_date, exit_date, status,
  ansmi_office, nv_office, team, member_type, qualification,
  last_name, first_name, tax_code, phone, email,
  residence_address, residence_zip, residence_city, residence_province,
  birth_place, birth_province, birth_date, ansmi_card_number, nv_card_number, pc_insurance
) values (
  '1',
  'E',
  '2018-09-03',
  NULL,
  'attivo',
  'CHIANOCCO',
  'CHIANOCCO',
  'VALSUSA',
  'S F V',
  'UCRS ISTR',
  'RONCO',
  'ROBERTO',
  'RNCRRT63H23L219W',
  '371 1500701',
  'rronco23@gmail.com',
  'VIA CANDIOLO, 15',
  '10127',
  'TORINO',
  'TO',
  'TORINO',
  'TO',
  '1963-06-23',
  '0292',
  '001/18',
  'X'
)
on conflict (tax_code) do update set
  reg_number = excluded.reg_number,
  reg_type = excluded.reg_type,
  entry_date = excluded.entry_date,
  exit_date = excluded.exit_date,
  status = excluded.status,
  ansmi_office = excluded.ansmi_office,
  nv_office = excluded.nv_office,
  team = excluded.team,
  member_type = excluded.member_type,
  qualification = excluded.qualification,
  last_name = excluded.last_name,
  first_name = excluded.first_name,
  phone = excluded.phone,
  email = excluded.email,
  residence_address = excluded.residence_address,
  residence_zip = excluded.residence_zip,
  residence_city = excluded.residence_city,
  residence_province = excluded.residence_province,
  birth_place = excluded.birth_place,
  birth_province = excluded.birth_province,
  birth_date = excluded.birth_date,
  ansmi_card_number = excluded.ansmi_card_number,
  nv_card_number = excluded.nv_card_number,
  pc_insurance = excluded.pc_insurance;

insert into public.dogs (
  volunteer_id, name, breed, sex, microchip, loi_code, pedigree_name, birth_date,
  enci_booklet_number, enci_sup_license, enci_mac_license, medical_certificate, vaccinations
)
select
  v.id,
  'WARM INDIAN CHINOOK',
  'GOLDEN RETRIEVER',
  'M',
  '380260080302018',
  '15/68863',
  'WARM INDIAN CHINOOK',
  '2015-03-05',
  '184577',
  '1213',
  NULL,
  NULL,
  'OK'
from public.volunteers v
where v.tax_code = 'RNCRRT63H23L219W'
on conflict (microchip) do update set
  volunteer_id = excluded.volunteer_id,
  name = excluded.name,
  breed = excluded.breed,
  sex = excluded.sex,
  loi_code = excluded.loi_code,
  pedigree_name = excluded.pedigree_name,
  birth_date = excluded.birth_date,
  enci_booklet_number = excluded.enci_booklet_number,
  enci_sup_license = excluded.enci_sup_license,
  enci_mac_license = excluded.enci_mac_license,
  medical_certificate = excluded.medical_certificate,
  vaccinations = excluded.vaccinations;

insert into public.volunteers (
  reg_number, reg_type, entry_date, exit_date, status,
  ansmi_office, nv_office, team, member_type, qualification,
  last_name, first_name, tax_code, phone, email,
  residence_address, residence_zip, residence_city, residence_province,
  birth_place, birth_province, birth_date, ansmi_card_number, nv_card_number, pc_insurance
) values (
  '2',
  'E',
  '2018-10-01',
  NULL,
  'attivo',
  'TORINO',
  'CHIANOCCO',
  'VALSUSA',
  'S F',
  'SOCIO FONDAT.',
  'BAUSANO',
  'CARLO',
  'BSNCRL84T13C665K',
  '328 2569211',
  'karket84@libero.it',
  'LOCALITÀ TABBIA, 43',
  '10020',
  'VERRUA SAVOIA',
  'TO',
  'CHIVASSO',
  'TO',
  '1984-12-13',
  NULL,
  NULL,
  NULL
)
on conflict (tax_code) do update set
  reg_number = excluded.reg_number,
  reg_type = excluded.reg_type,
  entry_date = excluded.entry_date,
  exit_date = excluded.exit_date,
  status = excluded.status,
  ansmi_office = excluded.ansmi_office,
  nv_office = excluded.nv_office,
  team = excluded.team,
  member_type = excluded.member_type,
  qualification = excluded.qualification,
  last_name = excluded.last_name,
  first_name = excluded.first_name,
  phone = excluded.phone,
  email = excluded.email,
  residence_address = excluded.residence_address,
  residence_zip = excluded.residence_zip,
  residence_city = excluded.residence_city,
  residence_province = excluded.residence_province,
  birth_place = excluded.birth_place,
  birth_province = excluded.birth_province,
  birth_date = excluded.birth_date,
  ansmi_card_number = excluded.ansmi_card_number,
  nv_card_number = excluded.nv_card_number,
  pc_insurance = excluded.pc_insurance;

insert into public.volunteers (
  reg_number, reg_type, entry_date, exit_date, status,
  ansmi_office, nv_office, team, member_type, qualification,
  last_name, first_name, tax_code, phone, email,
  residence_address, residence_zip, residence_city, residence_province,
  birth_place, birth_province, birth_date, ansmi_card_number, nv_card_number, pc_insurance
) values (
  '3',
  'E',
  '2018-10-01',
  NULL,
  'attivo',
  'TORINO',
  'CHIANOCCO',
  'VALSUSA',
  'S F',
  'SOCIO FONDAT.',
  'BOLZAN',
  'WALTER',
  'BLZWTR70L07L219H',
  '336 390903',
  'bolzan.geom.walter@tiscali.it',
  'VIA RIVALTA, 6/BIS',
  '10040',
  'VOLVERA',
  'TO',
  'TORINO',
  'TO',
  '1970-07-07',
  NULL,
  NULL,
  NULL
)
on conflict (tax_code) do update set
  reg_number = excluded.reg_number,
  reg_type = excluded.reg_type,
  entry_date = excluded.entry_date,
  exit_date = excluded.exit_date,
  status = excluded.status,
  ansmi_office = excluded.ansmi_office,
  nv_office = excluded.nv_office,
  team = excluded.team,
  member_type = excluded.member_type,
  qualification = excluded.qualification,
  last_name = excluded.last_name,
  first_name = excluded.first_name,
  phone = excluded.phone,
  email = excluded.email,
  residence_address = excluded.residence_address,
  residence_zip = excluded.residence_zip,
  residence_city = excluded.residence_city,
  residence_province = excluded.residence_province,
  birth_place = excluded.birth_place,
  birth_province = excluded.birth_province,
  birth_date = excluded.birth_date,
  ansmi_card_number = excluded.ansmi_card_number,
  nv_card_number = excluded.nv_card_number,
  pc_insurance = excluded.pc_insurance;

insert into public.volunteers (
  reg_number, reg_type, entry_date, exit_date, status,
  ansmi_office, nv_office, team, member_type, qualification,
  last_name, first_name, tax_code, phone, email,
  residence_address, residence_zip, residence_city, residence_province,
  birth_place, birth_province, birth_date, ansmi_card_number, nv_card_number, pc_insurance
) values (
  '4',
  'E',
  '2018-10-01',
  NULL,
  'attivo',
  'TORINO',
  'CHIANOCCO',
  'VALSUSA',
  'S F',
  'SOCIO FONDAT.',
  'CAPPONE',
  'MASSIMO',
  'CPPMSM56C23L219A',
  '335 6716556',
  'massimocappone56@gmail.com',
  'VIA FRAVAGNANO, 169',
  '10020',
  'VERRUA SAVOIA',
  'TO',
  'TORINO',
  'TO',
  '1956-03-23',
  NULL,
  NULL,
  NULL
)
on conflict (tax_code) do update set
  reg_number = excluded.reg_number,
  reg_type = excluded.reg_type,
  entry_date = excluded.entry_date,
  exit_date = excluded.exit_date,
  status = excluded.status,
  ansmi_office = excluded.ansmi_office,
  nv_office = excluded.nv_office,
  team = excluded.team,
  member_type = excluded.member_type,
  qualification = excluded.qualification,
  last_name = excluded.last_name,
  first_name = excluded.first_name,
  phone = excluded.phone,
  email = excluded.email,
  residence_address = excluded.residence_address,
  residence_zip = excluded.residence_zip,
  residence_city = excluded.residence_city,
  residence_province = excluded.residence_province,
  birth_place = excluded.birth_place,
  birth_province = excluded.birth_province,
  birth_date = excluded.birth_date,
  ansmi_card_number = excluded.ansmi_card_number,
  nv_card_number = excluded.nv_card_number,
  pc_insurance = excluded.pc_insurance;

insert into public.volunteers (
  reg_number, reg_type, entry_date, exit_date, status,
  ansmi_office, nv_office, team, member_type, qualification,
  last_name, first_name, tax_code, phone, email,
  residence_address, residence_zip, residence_city, residence_province,
  birth_place, birth_province, birth_date, ansmi_card_number, nv_card_number, pc_insurance
) values (
  '5',
  'E',
  '2018-10-01',
  NULL,
  'attivo',
  'TORINO',
  'CHIANOCCO',
  'VALSUSA',
  'S F',
  'SOCIO FONDAT.',
  'FABBRICATORE',
  'FABIO',
  'FBBFBA62B24L219H',
  '333 8913212',
  'fabio@fabbricatore.it',
  'PIAZZA GOZZANO, 15',
  '10100',
  'TORINO',
  'TO',
  'TORINO',
  'TO',
  '1962-02-24',
  NULL,
  NULL,
  NULL
)
on conflict (tax_code) do update set
  reg_number = excluded.reg_number,
  reg_type = excluded.reg_type,
  entry_date = excluded.entry_date,
  exit_date = excluded.exit_date,
  status = excluded.status,
  ansmi_office = excluded.ansmi_office,
  nv_office = excluded.nv_office,
  team = excluded.team,
  member_type = excluded.member_type,
  qualification = excluded.qualification,
  last_name = excluded.last_name,
  first_name = excluded.first_name,
  phone = excluded.phone,
  email = excluded.email,
  residence_address = excluded.residence_address,
  residence_zip = excluded.residence_zip,
  residence_city = excluded.residence_city,
  residence_province = excluded.residence_province,
  birth_place = excluded.birth_place,
  birth_province = excluded.birth_province,
  birth_date = excluded.birth_date,
  ansmi_card_number = excluded.ansmi_card_number,
  nv_card_number = excluded.nv_card_number,
  pc_insurance = excluded.pc_insurance;

insert into public.volunteers (
  reg_number, reg_type, entry_date, exit_date, status,
  ansmi_office, nv_office, team, member_type, qualification,
  last_name, first_name, tax_code, phone, email,
  residence_address, residence_zip, residence_city, residence_province,
  birth_place, birth_province, birth_date, ansmi_card_number, nv_card_number, pc_insurance
) values (
  '6',
  'E',
  '2018-10-01',
  NULL,
  'attivo',
  'TORINO',
  'CHIANOCCO',
  'VALSUSA',
  'S F',
  'SOCIO FONDAT.',
  'GIACHINO',
  'ACHILLE MARIA',
  'GCHCLL56B11L219F',
  '349 3163757',
  'ansmi@sanitamilitare.it',
  'VIA ALFIERI, 56',
  '14023',
  'COCCONATO',
  'AT',
  'TORINO',
  'TO',
  '1956-02-11',
  NULL,
  NULL,
  NULL
)
on conflict (tax_code) do update set
  reg_number = excluded.reg_number,
  reg_type = excluded.reg_type,
  entry_date = excluded.entry_date,
  exit_date = excluded.exit_date,
  status = excluded.status,
  ansmi_office = excluded.ansmi_office,
  nv_office = excluded.nv_office,
  team = excluded.team,
  member_type = excluded.member_type,
  qualification = excluded.qualification,
  last_name = excluded.last_name,
  first_name = excluded.first_name,
  phone = excluded.phone,
  email = excluded.email,
  residence_address = excluded.residence_address,
  residence_zip = excluded.residence_zip,
  residence_city = excluded.residence_city,
  residence_province = excluded.residence_province,
  birth_place = excluded.birth_place,
  birth_province = excluded.birth_province,
  birth_date = excluded.birth_date,
  ansmi_card_number = excluded.ansmi_card_number,
  nv_card_number = excluded.nv_card_number,
  pc_insurance = excluded.pc_insurance;

insert into public.volunteers (
  reg_number, reg_type, entry_date, exit_date, status,
  ansmi_office, nv_office, team, member_type, qualification,
  last_name, first_name, tax_code, phone, email,
  residence_address, residence_zip, residence_city, residence_province,
  birth_place, birth_province, birth_date, ansmi_card_number, nv_card_number, pc_insurance
) values (
  '7',
  'E',
  '2018-10-01',
  NULL,
  'attivo',
  'CASTELLAMONTE',
  'CHIANOCCO',
  'VALSUSA',
  'S F',
  'SOCIO FONDAT.',
  'MADONNA',
  'DEFENDENTE',
  'MDNDND49A14C241D',
  '340 2445423',
  'ansmi.canavese@sanitamilitare.it',
  'CORSO PALERMO, 10',
  '10100',
  'TORINO',
  'TO',
  'CASTELNUOVO NIGRA',
  'TO',
  '1949-01-14',
  NULL,
  NULL,
  NULL
)
on conflict (tax_code) do update set
  reg_number = excluded.reg_number,
  reg_type = excluded.reg_type,
  entry_date = excluded.entry_date,
  exit_date = excluded.exit_date,
  status = excluded.status,
  ansmi_office = excluded.ansmi_office,
  nv_office = excluded.nv_office,
  team = excluded.team,
  member_type = excluded.member_type,
  qualification = excluded.qualification,
  last_name = excluded.last_name,
  first_name = excluded.first_name,
  phone = excluded.phone,
  email = excluded.email,
  residence_address = excluded.residence_address,
  residence_zip = excluded.residence_zip,
  residence_city = excluded.residence_city,
  residence_province = excluded.residence_province,
  birth_place = excluded.birth_place,
  birth_province = excluded.birth_province,
  birth_date = excluded.birth_date,
  ansmi_card_number = excluded.ansmi_card_number,
  nv_card_number = excluded.nv_card_number,
  pc_insurance = excluded.pc_insurance;

insert into public.volunteers (
  reg_number, reg_type, entry_date, exit_date, status,
  ansmi_office, nv_office, team, member_type, qualification,
  last_name, first_name, tax_code, phone, email,
  residence_address, residence_zip, residence_city, residence_province,
  birth_place, birth_province, birth_date, ansmi_card_number, nv_card_number, pc_insurance
) values (
  '8',
  'E',
  '2018-10-01',
  NULL,
  'attivo',
  'TORINO',
  'CHIANOCCO',
  'VALSUSA',
  'S F',
  'SOCIO FONDAT.',
  'PRATI',
  'STEFANO',
  'PRTSFN53H07B885H',
  '366 1290997',
  'croceverdemurisengo@libero.it',
  'VIA SORINA, 12',
  '15020',
  'MURISENGO',
  'AL',
  'CASALE MONFERRATO',
  'AL',
  '1953-06-07',
  NULL,
  NULL,
  NULL
)
on conflict (tax_code) do update set
  reg_number = excluded.reg_number,
  reg_type = excluded.reg_type,
  entry_date = excluded.entry_date,
  exit_date = excluded.exit_date,
  status = excluded.status,
  ansmi_office = excluded.ansmi_office,
  nv_office = excluded.nv_office,
  team = excluded.team,
  member_type = excluded.member_type,
  qualification = excluded.qualification,
  last_name = excluded.last_name,
  first_name = excluded.first_name,
  phone = excluded.phone,
  email = excluded.email,
  residence_address = excluded.residence_address,
  residence_zip = excluded.residence_zip,
  residence_city = excluded.residence_city,
  residence_province = excluded.residence_province,
  birth_place = excluded.birth_place,
  birth_province = excluded.birth_province,
  birth_date = excluded.birth_date,
  ansmi_card_number = excluded.ansmi_card_number,
  nv_card_number = excluded.nv_card_number,
  pc_insurance = excluded.pc_insurance;

insert into public.volunteers (
  reg_number, reg_type, entry_date, exit_date, status,
  ansmi_office, nv_office, team, member_type, qualification,
  last_name, first_name, tax_code, phone, email,
  residence_address, residence_zip, residence_city, residence_province,
  birth_place, birth_province, birth_date, ansmi_card_number, nv_card_number, pc_insurance
) values (
  '9',
  'E',
  '2018-10-01',
  NULL,
  'attivo',
  'TORINO',
  'CHIANOCCO',
  'VALSUSA',
  'S F',
  'SOCIO FONDAT.',
  'RIBAUDO',
  'GIANCARLO',
  'RBDGLR51D11B429V',
  '345 6307911',
  'carlo.riba@tiscali.it',
  'VIA MASSIMO D''AZEGLIO, 75',
  '13040',
  'FONTANETO PO',
  'VC',
  'CALTANISSETTA',
  'CL',
  '1951-04-11',
  NULL,
  NULL,
  NULL
)
on conflict (tax_code) do update set
  reg_number = excluded.reg_number,
  reg_type = excluded.reg_type,
  entry_date = excluded.entry_date,
  exit_date = excluded.exit_date,
  status = excluded.status,
  ansmi_office = excluded.ansmi_office,
  nv_office = excluded.nv_office,
  team = excluded.team,
  member_type = excluded.member_type,
  qualification = excluded.qualification,
  last_name = excluded.last_name,
  first_name = excluded.first_name,
  phone = excluded.phone,
  email = excluded.email,
  residence_address = excluded.residence_address,
  residence_zip = excluded.residence_zip,
  residence_city = excluded.residence_city,
  residence_province = excluded.residence_province,
  birth_place = excluded.birth_place,
  birth_province = excluded.birth_province,
  birth_date = excluded.birth_date,
  ansmi_card_number = excluded.ansmi_card_number,
  nv_card_number = excluded.nv_card_number,
  pc_insurance = excluded.pc_insurance;

insert into public.volunteers (
  reg_number, reg_type, entry_date, exit_date, status,
  ansmi_office, nv_office, team, member_type, qualification,
  last_name, first_name, tax_code, phone, email,
  residence_address, residence_zip, residence_city, residence_province,
  birth_place, birth_province, birth_date, ansmi_card_number, nv_card_number, pc_insurance
) values (
  '10',
  'E',
  '2018-10-01',
  NULL,
  'attivo',
  'TORINO',
  'CHIANOCCO',
  'VALSUSA',
  'S F',
  'SOCIO FONDAT.',
  'STEVANIN',
  'CLAUDIO',
  'STVCLD59E27L219I',
  '333 3953255',
  'claudio.stevanin@alice.it',
  'VIA UMBERTO I, 75',
  '15020',
  'MURISENGO',
  'AL',
  'TORINO',
  'TO',
  '1959-05-27',
  NULL,
  NULL,
  NULL
)
on conflict (tax_code) do update set
  reg_number = excluded.reg_number,
  reg_type = excluded.reg_type,
  entry_date = excluded.entry_date,
  exit_date = excluded.exit_date,
  status = excluded.status,
  ansmi_office = excluded.ansmi_office,
  nv_office = excluded.nv_office,
  team = excluded.team,
  member_type = excluded.member_type,
  qualification = excluded.qualification,
  last_name = excluded.last_name,
  first_name = excluded.first_name,
  phone = excluded.phone,
  email = excluded.email,
  residence_address = excluded.residence_address,
  residence_zip = excluded.residence_zip,
  residence_city = excluded.residence_city,
  residence_province = excluded.residence_province,
  birth_place = excluded.birth_place,
  birth_province = excluded.birth_province,
  birth_date = excluded.birth_date,
  ansmi_card_number = excluded.ansmi_card_number,
  nv_card_number = excluded.nv_card_number,
  pc_insurance = excluded.pc_insurance;

insert into public.volunteers (
  reg_number, reg_type, entry_date, exit_date, status,
  ansmi_office, nv_office, team, member_type, qualification,
  last_name, first_name, tax_code, phone, email,
  residence_address, residence_zip, residence_city, residence_province,
  birth_place, birth_province, birth_date, ansmi_card_number, nv_card_number, pc_insurance
) values (
  '11',
  'E',
  '2018-10-01',
  NULL,
  'attivo',
  'TORINO',
  'CHIANOCCO',
  'VALSUSA',
  'S F',
  'SOCIO FONDAT.',
  'TRIMBOLI',
  'LORIS',
  'TRMLRS61C29L219M',
  '334 3886513',
  'loris2961@hotmail.it',
  'CASCINA FONTANA, 2',
  '13100',
  'VERCELLI',
  'VC',
  'TORINO',
  'TO',
  '1961-03-29',
  NULL,
  NULL,
  NULL
)
on conflict (tax_code) do update set
  reg_number = excluded.reg_number,
  reg_type = excluded.reg_type,
  entry_date = excluded.entry_date,
  exit_date = excluded.exit_date,
  status = excluded.status,
  ansmi_office = excluded.ansmi_office,
  nv_office = excluded.nv_office,
  team = excluded.team,
  member_type = excluded.member_type,
  qualification = excluded.qualification,
  last_name = excluded.last_name,
  first_name = excluded.first_name,
  phone = excluded.phone,
  email = excluded.email,
  residence_address = excluded.residence_address,
  residence_zip = excluded.residence_zip,
  residence_city = excluded.residence_city,
  residence_province = excluded.residence_province,
  birth_place = excluded.birth_place,
  birth_province = excluded.birth_province,
  birth_date = excluded.birth_date,
  ansmi_card_number = excluded.ansmi_card_number,
  nv_card_number = excluded.nv_card_number,
  pc_insurance = excluded.pc_insurance;

insert into public.volunteers (
  reg_number, reg_type, entry_date, exit_date, status,
  ansmi_office, nv_office, team, member_type, qualification,
  last_name, first_name, tax_code, phone, email,
  residence_address, residence_zip, residence_city, residence_province,
  birth_place, birth_province, birth_date, ansmi_card_number, nv_card_number, pc_insurance
) values (
  '12',
  'E',
  '2020-03-23',
  NULL,
  'attivo',
  'CHIANOCCO',
  'CHIANOCCO',
  'VALSUSA',
  'S V',
  'UCRS',
  'IMPERATRICE',
  'GIAN GRANCO',
  'MPRGFR70B05L219P',
  '348 6600517',
  'g.f.imperatrice@gmail.com',
  'VIA SOCRATE, 31',
  '10088',
  'VOLPIANO',
  'TO',
  'TORINO',
  'TO',
  '1970-02-05',
  '0326',
  '010/20',
  'X'
)
on conflict (tax_code) do update set
  reg_number = excluded.reg_number,
  reg_type = excluded.reg_type,
  entry_date = excluded.entry_date,
  exit_date = excluded.exit_date,
  status = excluded.status,
  ansmi_office = excluded.ansmi_office,
  nv_office = excluded.nv_office,
  team = excluded.team,
  member_type = excluded.member_type,
  qualification = excluded.qualification,
  last_name = excluded.last_name,
  first_name = excluded.first_name,
  phone = excluded.phone,
  email = excluded.email,
  residence_address = excluded.residence_address,
  residence_zip = excluded.residence_zip,
  residence_city = excluded.residence_city,
  residence_province = excluded.residence_province,
  birth_place = excluded.birth_place,
  birth_province = excluded.birth_province,
  birth_date = excluded.birth_date,
  ansmi_card_number = excluded.ansmi_card_number,
  nv_card_number = excluded.nv_card_number,
  pc_insurance = excluded.pc_insurance;

insert into public.dogs (
  volunteer_id, name, breed, sex, microchip, loi_code, pedigree_name, birth_date,
  enci_booklet_number, enci_sup_license, enci_mac_license, medical_certificate, vaccinations
)
select
  v.id,
  'HINCKLEY',
  'GOLDEN RETRIEVER',
  'M',
  '380260120150317',
  '19/167435',
  'HINCKLEY',
  '2019-07-07',
  NULL,
  NULL,
  NULL,
  NULL,
  NULL
from public.volunteers v
where v.tax_code = 'MPRGFR70B05L219P'
on conflict (microchip) do update set
  volunteer_id = excluded.volunteer_id,
  name = excluded.name,
  breed = excluded.breed,
  sex = excluded.sex,
  loi_code = excluded.loi_code,
  pedigree_name = excluded.pedigree_name,
  birth_date = excluded.birth_date,
  enci_booklet_number = excluded.enci_booklet_number,
  enci_sup_license = excluded.enci_sup_license,
  enci_mac_license = excluded.enci_mac_license,
  medical_certificate = excluded.medical_certificate,
  vaccinations = excluded.vaccinations;

insert into public.volunteers (
  reg_number, reg_type, entry_date, exit_date, status,
  ansmi_office, nv_office, team, member_type, qualification,
  last_name, first_name, tax_code, phone, email,
  residence_address, residence_zip, residence_city, residence_province,
  birth_place, birth_province, birth_date, ansmi_card_number, nv_card_number, pc_insurance
) values (
  '13',
  'U',
  '2020-08-04',
  '2025-02-01',
  'uscito',
  'CHIANOCCO',
  'CHIANOCCO',
  'VALSUSA',
  NULL,
  'UCRS',
  'LERDA',
  'MARCO',
  'LRDMRC50H18G674H',
  '347 2254115',
  'marco.lerda@hotmail.it',
  'VIA OROPA, 6C',
  '10040',
  'RIVALTA DI TORINO',
  'TO',
  'PINEROLO',
  'TO',
  '1950-06-18',
  '0340',
  '016/20',
  'X'
)
on conflict (tax_code) do update set
  reg_number = excluded.reg_number,
  reg_type = excluded.reg_type,
  entry_date = excluded.entry_date,
  exit_date = excluded.exit_date,
  status = excluded.status,
  ansmi_office = excluded.ansmi_office,
  nv_office = excluded.nv_office,
  team = excluded.team,
  member_type = excluded.member_type,
  qualification = excluded.qualification,
  last_name = excluded.last_name,
  first_name = excluded.first_name,
  phone = excluded.phone,
  email = excluded.email,
  residence_address = excluded.residence_address,
  residence_zip = excluded.residence_zip,
  residence_city = excluded.residence_city,
  residence_province = excluded.residence_province,
  birth_place = excluded.birth_place,
  birth_province = excluded.birth_province,
  birth_date = excluded.birth_date,
  ansmi_card_number = excluded.ansmi_card_number,
  nv_card_number = excluded.nv_card_number,
  pc_insurance = excluded.pc_insurance;

insert into public.volunteers (
  reg_number, reg_type, entry_date, exit_date, status,
  ansmi_office, nv_office, team, member_type, qualification,
  last_name, first_name, tax_code, phone, email,
  residence_address, residence_zip, residence_city, residence_province,
  birth_place, birth_province, birth_date, ansmi_card_number, nv_card_number, pc_insurance
) values (
  '14',
  'E',
  '2020-11-08',
  NULL,
  'attivo',
  'CHIANOCCO',
  'CHIANOCCO',
  'VARESE',
  'S V',
  'UCRS ISTR',
  'AUSILI',
  'SERGIO',
  'SLASRG65A28H501O',
  '340 7777699',
  'ausili.sergio@gmail.com',
  'VIA VIGNETTA, 10',
  '21013',
  'GALLARATE',
  'VA',
  'ROMA',
  'RM',
  '1965-01-28',
  '0345',
  '021/20',
  'X'
)
on conflict (tax_code) do update set
  reg_number = excluded.reg_number,
  reg_type = excluded.reg_type,
  entry_date = excluded.entry_date,
  exit_date = excluded.exit_date,
  status = excluded.status,
  ansmi_office = excluded.ansmi_office,
  nv_office = excluded.nv_office,
  team = excluded.team,
  member_type = excluded.member_type,
  qualification = excluded.qualification,
  last_name = excluded.last_name,
  first_name = excluded.first_name,
  phone = excluded.phone,
  email = excluded.email,
  residence_address = excluded.residence_address,
  residence_zip = excluded.residence_zip,
  residence_city = excluded.residence_city,
  residence_province = excluded.residence_province,
  birth_place = excluded.birth_place,
  birth_province = excluded.birth_province,
  birth_date = excluded.birth_date,
  ansmi_card_number = excluded.ansmi_card_number,
  nv_card_number = excluded.nv_card_number,
  pc_insurance = excluded.pc_insurance;

insert into public.dogs (
  volunteer_id, name, breed, sex, microchip, loi_code, pedigree_name, birth_date,
  enci_booklet_number, enci_sup_license, enci_mac_license, medical_certificate, vaccinations
)
select
  v.id,
  'CODY',
  'METICCIO',
  'M',
  '380260002001774',
  NULL,
  'CODY',
  '2013-01-10',
  NULL,
  NULL,
  NULL,
  NULL,
  NULL
from public.volunteers v
where v.tax_code = 'SLASRG65A28H501O'
on conflict (microchip) do update set
  volunteer_id = excluded.volunteer_id,
  name = excluded.name,
  breed = excluded.breed,
  sex = excluded.sex,
  loi_code = excluded.loi_code,
  pedigree_name = excluded.pedigree_name,
  birth_date = excluded.birth_date,
  enci_booklet_number = excluded.enci_booklet_number,
  enci_sup_license = excluded.enci_sup_license,
  enci_mac_license = excluded.enci_mac_license,
  medical_certificate = excluded.medical_certificate,
  vaccinations = excluded.vaccinations;

insert into public.dogs (
  volunteer_id, name, breed, sex, microchip, loi_code, pedigree_name, birth_date,
  enci_booklet_number, enci_sup_license, enci_mac_license, medical_certificate, vaccinations
)
select
  v.id,
  '(FLAY) SHOSANNA DREYFUS INGLORIOUS BASTERDS',
  'PASTORE OLANDESE',
  'F',
  '380260101367286',
  'LO19112316',
  '(FLAY) SHOSANNA DREYFUS INGLORIOUS BASTERDS',
  '2019-05-01',
  NULL,
  NULL,
  NULL,
  NULL,
  NULL
from public.volunteers v
where v.tax_code = 'SLASRG65A28H501O'
on conflict (microchip) do update set
  volunteer_id = excluded.volunteer_id,
  name = excluded.name,
  breed = excluded.breed,
  sex = excluded.sex,
  loi_code = excluded.loi_code,
  pedigree_name = excluded.pedigree_name,
  birth_date = excluded.birth_date,
  enci_booklet_number = excluded.enci_booklet_number,
  enci_sup_license = excluded.enci_sup_license,
  enci_mac_license = excluded.enci_mac_license,
  medical_certificate = excluded.medical_certificate,
  vaccinations = excluded.vaccinations;

insert into public.volunteers (
  reg_number, reg_type, entry_date, exit_date, status,
  ansmi_office, nv_office, team, member_type, qualification,
  last_name, first_name, tax_code, phone, email,
  residence_address, residence_zip, residence_city, residence_province,
  birth_place, birth_province, birth_date, ansmi_card_number, nv_card_number, pc_insurance
) values (
  '15',
  'E',
  '2020-11-08',
  NULL,
  'attivo',
  'CHIANOCCO',
  'CHIANOCCO',
  'VARESE',
  'S V',
  'UCRS ISTR',
  'CHECCHI',
  'CLAUDIA',
  'CHCCLD76D58D869Z',
  '329 2192669',
  'claudiachecchi76@gmail.com',
  'VIA VIGNETTA, 10',
  '21013',
  'GALLARATE',
  'VA',
  'GALLARATE',
  'VA',
  '1976-04-18',
  '0346',
  '022/20',
  'X'
)
on conflict (tax_code) do update set
  reg_number = excluded.reg_number,
  reg_type = excluded.reg_type,
  entry_date = excluded.entry_date,
  exit_date = excluded.exit_date,
  status = excluded.status,
  ansmi_office = excluded.ansmi_office,
  nv_office = excluded.nv_office,
  team = excluded.team,
  member_type = excluded.member_type,
  qualification = excluded.qualification,
  last_name = excluded.last_name,
  first_name = excluded.first_name,
  phone = excluded.phone,
  email = excluded.email,
  residence_address = excluded.residence_address,
  residence_zip = excluded.residence_zip,
  residence_city = excluded.residence_city,
  residence_province = excluded.residence_province,
  birth_place = excluded.birth_place,
  birth_province = excluded.birth_province,
  birth_date = excluded.birth_date,
  ansmi_card_number = excluded.ansmi_card_number,
  nv_card_number = excluded.nv_card_number,
  pc_insurance = excluded.pc_insurance;

insert into public.dogs (
  volunteer_id, name, breed, sex, microchip, loi_code, pedigree_name, birth_date,
  enci_booklet_number, enci_sup_license, enci_mac_license, medical_certificate, vaccinations
)
select
  v.id,
  'ONE MORE TRY',
  'LABRADOR',
  'F',
  '380260043746672',
  'LO1945979',
  'ONE MORE TRY',
  '2018-12-16',
  NULL,
  NULL,
  NULL,
  NULL,
  NULL
from public.volunteers v
where v.tax_code = 'CHCCLD76D58D869Z'
on conflict (microchip) do update set
  volunteer_id = excluded.volunteer_id,
  name = excluded.name,
  breed = excluded.breed,
  sex = excluded.sex,
  loi_code = excluded.loi_code,
  pedigree_name = excluded.pedigree_name,
  birth_date = excluded.birth_date,
  enci_booklet_number = excluded.enci_booklet_number,
  enci_sup_license = excluded.enci_sup_license,
  enci_mac_license = excluded.enci_mac_license,
  medical_certificate = excluded.medical_certificate,
  vaccinations = excluded.vaccinations;

insert into public.volunteers (
  reg_number, reg_type, entry_date, exit_date, status,
  ansmi_office, nv_office, team, member_type, qualification,
  last_name, first_name, tax_code, phone, email,
  residence_address, residence_zip, residence_city, residence_province,
  birth_place, birth_province, birth_date, ansmi_card_number, nv_card_number, pc_insurance
) values (
  '16',
  'U',
  '2021-05-25',
  '2024-08-13',
  'uscito',
  'CHIANOCCO',
  'CHIANOCCO',
  'VALSUSA',
  NULL,
  'UCRS',
  'BIGI',
  'MASSIMO',
  'BGIMSM71M31L219I',
  '348 8065122',
  'maxtelenergy@gmail.com',
  'VIA BARDONECCHIA, 28',
  '10056',
  'OULX',
  'TO',
  'TORINO',
  'TO',
  '1971-08-31',
  NULL,
  '027/21',
  'X'
)
on conflict (tax_code) do update set
  reg_number = excluded.reg_number,
  reg_type = excluded.reg_type,
  entry_date = excluded.entry_date,
  exit_date = excluded.exit_date,
  status = excluded.status,
  ansmi_office = excluded.ansmi_office,
  nv_office = excluded.nv_office,
  team = excluded.team,
  member_type = excluded.member_type,
  qualification = excluded.qualification,
  last_name = excluded.last_name,
  first_name = excluded.first_name,
  phone = excluded.phone,
  email = excluded.email,
  residence_address = excluded.residence_address,
  residence_zip = excluded.residence_zip,
  residence_city = excluded.residence_city,
  residence_province = excluded.residence_province,
  birth_place = excluded.birth_place,
  birth_province = excluded.birth_province,
  birth_date = excluded.birth_date,
  ansmi_card_number = excluded.ansmi_card_number,
  nv_card_number = excluded.nv_card_number,
  pc_insurance = excluded.pc_insurance;

insert into public.dogs (
  volunteer_id, name, breed, sex, microchip, loi_code, pedigree_name, birth_date,
  enci_booklet_number, enci_sup_license, enci_mac_license, medical_certificate, vaccinations
)
select
  v.id,
  'MILA',
  'METICCIO',
  'F',
  '380260002950870',
  NULL,
  'MILA',
  '2018-09-28',
  '268181',
  NULL,
  NULL,
  NULL,
  NULL
from public.volunteers v
where v.tax_code = 'BGIMSM71M31L219I'
on conflict (microchip) do update set
  volunteer_id = excluded.volunteer_id,
  name = excluded.name,
  breed = excluded.breed,
  sex = excluded.sex,
  loi_code = excluded.loi_code,
  pedigree_name = excluded.pedigree_name,
  birth_date = excluded.birth_date,
  enci_booklet_number = excluded.enci_booklet_number,
  enci_sup_license = excluded.enci_sup_license,
  enci_mac_license = excluded.enci_mac_license,
  medical_certificate = excluded.medical_certificate,
  vaccinations = excluded.vaccinations;

insert into public.volunteers (
  reg_number, reg_type, entry_date, exit_date, status,
  ansmi_office, nv_office, team, member_type, qualification,
  last_name, first_name, tax_code, phone, email,
  residence_address, residence_zip, residence_city, residence_province,
  birth_place, birth_province, birth_date, ansmi_card_number, nv_card_number, pc_insurance
) values (
  '17',
  'E',
  '2021-05-25',
  NULL,
  'attivo',
  'CHIANOCCO',
  'CHIANOCCO',
  'VALSUSA',
  'S V',
  'UCRS ISTR',
  'LAMI',
  'SIMONA',
  'LMASMN74C61D458E',
  '340 3317088',
  'lamisimona@gmail.com',
  'VIA BARDONECCHIA, 28',
  '10056',
  'OULX',
  'TO',
  'FAENZA',
  'RA',
  '1974-03-21',
  NULL,
  '028/21',
  'X'
)
on conflict (tax_code) do update set
  reg_number = excluded.reg_number,
  reg_type = excluded.reg_type,
  entry_date = excluded.entry_date,
  exit_date = excluded.exit_date,
  status = excluded.status,
  ansmi_office = excluded.ansmi_office,
  nv_office = excluded.nv_office,
  team = excluded.team,
  member_type = excluded.member_type,
  qualification = excluded.qualification,
  last_name = excluded.last_name,
  first_name = excluded.first_name,
  phone = excluded.phone,
  email = excluded.email,
  residence_address = excluded.residence_address,
  residence_zip = excluded.residence_zip,
  residence_city = excluded.residence_city,
  residence_province = excluded.residence_province,
  birth_place = excluded.birth_place,
  birth_province = excluded.birth_province,
  birth_date = excluded.birth_date,
  ansmi_card_number = excluded.ansmi_card_number,
  nv_card_number = excluded.nv_card_number,
  pc_insurance = excluded.pc_insurance;

insert into public.dogs (
  volunteer_id, name, breed, sex, microchip, loi_code, pedigree_name, birth_date,
  enci_booklet_number, enci_sup_license, enci_mac_license, medical_certificate, vaccinations
)
select
  v.id,
  'GELPBLU',
  'BORDER COLLIE',
  'F',
  '380260004315897',
  'LO20156522',
  'GELPBLU',
  '2020-09-05',
  '287339',
  '2739',
  NULL,
  'OK',
  'OK'
from public.volunteers v
where v.tax_code = 'LMASMN74C61D458E'
on conflict (microchip) do update set
  volunteer_id = excluded.volunteer_id,
  name = excluded.name,
  breed = excluded.breed,
  sex = excluded.sex,
  loi_code = excluded.loi_code,
  pedigree_name = excluded.pedigree_name,
  birth_date = excluded.birth_date,
  enci_booklet_number = excluded.enci_booklet_number,
  enci_sup_license = excluded.enci_sup_license,
  enci_mac_license = excluded.enci_mac_license,
  medical_certificate = excluded.medical_certificate,
  vaccinations = excluded.vaccinations;

insert into public.dogs (
  volunteer_id, name, breed, sex, microchip, loi_code, pedigree_name, birth_date,
  enci_booklet_number, enci_sup_license, enci_mac_license, medical_certificate, vaccinations
)
select
  v.id,
  'TEQUILA DI CASA NOSELLA',
  'PASTORE TEDESCO',
  'F',
  '380260044876122',
  '23/34146',
  'TEQUILA DI CASA NOSELLA',
  '2022-12-05',
  '290229',
  NULL,
  NULL,
  'OK',
  'OK'
from public.volunteers v
where v.tax_code = 'LMASMN74C61D458E'
on conflict (microchip) do update set
  volunteer_id = excluded.volunteer_id,
  name = excluded.name,
  breed = excluded.breed,
  sex = excluded.sex,
  loi_code = excluded.loi_code,
  pedigree_name = excluded.pedigree_name,
  birth_date = excluded.birth_date,
  enci_booklet_number = excluded.enci_booklet_number,
  enci_sup_license = excluded.enci_sup_license,
  enci_mac_license = excluded.enci_mac_license,
  medical_certificate = excluded.medical_certificate,
  vaccinations = excluded.vaccinations;

insert into public.volunteers (
  reg_number, reg_type, entry_date, exit_date, status,
  ansmi_office, nv_office, team, member_type, qualification,
  last_name, first_name, tax_code, phone, email,
  residence_address, residence_zip, residence_city, residence_province,
  birth_place, birth_province, birth_date, ansmi_card_number, nv_card_number, pc_insurance
) values (
  '18',
  'U',
  '2021-05-25',
  '2024-11-28',
  'uscito',
  'CHIANOCCO',
  'CHIANOCCO',
  'VALSUSA',
  NULL,
  'UCRS',
  'MARANGONI',
  'ALESSIO',
  'MRNLSS78A04L219N',
  '339 1222649',
  'alessio.marangoni@libero.it',
  'BORGATA RUATTA, 5',
  '10040',
  'RUBIANA',
  'TO',
  'TORINO',
  'TO',
  '1978-01-04',
  NULL,
  '029/21',
  NULL
)
on conflict (tax_code) do update set
  reg_number = excluded.reg_number,
  reg_type = excluded.reg_type,
  entry_date = excluded.entry_date,
  exit_date = excluded.exit_date,
  status = excluded.status,
  ansmi_office = excluded.ansmi_office,
  nv_office = excluded.nv_office,
  team = excluded.team,
  member_type = excluded.member_type,
  qualification = excluded.qualification,
  last_name = excluded.last_name,
  first_name = excluded.first_name,
  phone = excluded.phone,
  email = excluded.email,
  residence_address = excluded.residence_address,
  residence_zip = excluded.residence_zip,
  residence_city = excluded.residence_city,
  residence_province = excluded.residence_province,
  birth_place = excluded.birth_place,
  birth_province = excluded.birth_province,
  birth_date = excluded.birth_date,
  ansmi_card_number = excluded.ansmi_card_number,
  nv_card_number = excluded.nv_card_number,
  pc_insurance = excluded.pc_insurance;

insert into public.volunteers (
  reg_number, reg_type, entry_date, exit_date, status,
  ansmi_office, nv_office, team, member_type, qualification,
  last_name, first_name, tax_code, phone, email,
  residence_address, residence_zip, residence_city, residence_province,
  birth_place, birth_province, birth_date, ansmi_card_number, nv_card_number, pc_insurance
) values (
  '19',
  'U',
  '2021-12-15',
  '2024-11-28',
  'uscito',
  'CHIANOCCO',
  'CHIANOCCO',
  'VARESE',
  NULL,
  'UCRS',
  'SARTORIO',
  'MARCO',
  'SRTMRC97S10L682Q',
  '346 2877408',
  'kmarcosartorio97k@gmail.com',
  'VIA PIAVE, 10',
  '21030',
  'CUVIO',
  'VA',
  'VARESE',
  'VA',
  '1997-11-10',
  NULL,
  '032/21',
  'X'
)
on conflict (tax_code) do update set
  reg_number = excluded.reg_number,
  reg_type = excluded.reg_type,
  entry_date = excluded.entry_date,
  exit_date = excluded.exit_date,
  status = excluded.status,
  ansmi_office = excluded.ansmi_office,
  nv_office = excluded.nv_office,
  team = excluded.team,
  member_type = excluded.member_type,
  qualification = excluded.qualification,
  last_name = excluded.last_name,
  first_name = excluded.first_name,
  phone = excluded.phone,
  email = excluded.email,
  residence_address = excluded.residence_address,
  residence_zip = excluded.residence_zip,
  residence_city = excluded.residence_city,
  residence_province = excluded.residence_province,
  birth_place = excluded.birth_place,
  birth_province = excluded.birth_province,
  birth_date = excluded.birth_date,
  ansmi_card_number = excluded.ansmi_card_number,
  nv_card_number = excluded.nv_card_number,
  pc_insurance = excluded.pc_insurance;

insert into public.dogs (
  volunteer_id, name, breed, sex, microchip, loi_code, pedigree_name, birth_date,
  enci_booklet_number, enci_sup_license, enci_mac_license, medical_certificate, vaccinations
)
select
  v.id,
  'NEIGE',
  'AUSTRALIAN SHEPERD',
  'M',
  '380260101738760',
  'LO20181877',
  'NEIGE',
  '2020-11-26',
  NULL,
  NULL,
  NULL,
  '11/11/22',
  NULL
from public.volunteers v
where v.tax_code = 'SRTMRC97S10L682Q'
on conflict (microchip) do update set
  volunteer_id = excluded.volunteer_id,
  name = excluded.name,
  breed = excluded.breed,
  sex = excluded.sex,
  loi_code = excluded.loi_code,
  pedigree_name = excluded.pedigree_name,
  birth_date = excluded.birth_date,
  enci_booklet_number = excluded.enci_booklet_number,
  enci_sup_license = excluded.enci_sup_license,
  enci_mac_license = excluded.enci_mac_license,
  medical_certificate = excluded.medical_certificate,
  vaccinations = excluded.vaccinations;

insert into public.volunteers (
  reg_number, reg_type, entry_date, exit_date, status,
  ansmi_office, nv_office, team, member_type, qualification,
  last_name, first_name, tax_code, phone, email,
  residence_address, residence_zip, residence_city, residence_province,
  birth_place, birth_province, birth_date, ansmi_card_number, nv_card_number, pc_insurance
) values (
  '20',
  'U',
  '2022-01-19',
  '2025-02-01',
  'uscito',
  'CHIANOCCO',
  'CHIANOCCO',
  NULL,
  NULL,
  'PC',
  'AZZOLIN',
  'GUIDO',
  'ZZLGDU58B11L013X',
  '347 1901690',
  'gualeandre@gmail.com',
  'VIA ROSSERO, 5',
  '10050',
  'CHIANOCCO',
  'TO',
  'SUSA',
  'TO',
  '1958-02-11',
  NULL,
  '033/22',
  'X'
)
on conflict (tax_code) do update set
  reg_number = excluded.reg_number,
  reg_type = excluded.reg_type,
  entry_date = excluded.entry_date,
  exit_date = excluded.exit_date,
  status = excluded.status,
  ansmi_office = excluded.ansmi_office,
  nv_office = excluded.nv_office,
  team = excluded.team,
  member_type = excluded.member_type,
  qualification = excluded.qualification,
  last_name = excluded.last_name,
  first_name = excluded.first_name,
  phone = excluded.phone,
  email = excluded.email,
  residence_address = excluded.residence_address,
  residence_zip = excluded.residence_zip,
  residence_city = excluded.residence_city,
  residence_province = excluded.residence_province,
  birth_place = excluded.birth_place,
  birth_province = excluded.birth_province,
  birth_date = excluded.birth_date,
  ansmi_card_number = excluded.ansmi_card_number,
  nv_card_number = excluded.nv_card_number,
  pc_insurance = excluded.pc_insurance;

insert into public.volunteers (
  reg_number, reg_type, entry_date, exit_date, status,
  ansmi_office, nv_office, team, member_type, qualification,
  last_name, first_name, tax_code, phone, email,
  residence_address, residence_zip, residence_city, residence_province,
  birth_place, birth_province, birth_date, ansmi_card_number, nv_card_number, pc_insurance
) values (
  '21',
  'U',
  '2022-01-19',
  '2025-02-01',
  'uscito',
  'CHIANOCCO',
  'CHIANOCCO',
  NULL,
  NULL,
  'PC',
  'VAIR',
  'OSVALDO',
  'VRASLD70B06L219T',
  '349 7599779',
  'osvaldovair@alice.it',
  'VIA CAMPOSCIUTTO, 12',
  '10050',
  'CHIANOCCO',
  'TO',
  'TORINO',
  'TO',
  '1970-02-06',
  NULL,
  '035/22',
  'X'
)
on conflict (tax_code) do update set
  reg_number = excluded.reg_number,
  reg_type = excluded.reg_type,
  entry_date = excluded.entry_date,
  exit_date = excluded.exit_date,
  status = excluded.status,
  ansmi_office = excluded.ansmi_office,
  nv_office = excluded.nv_office,
  team = excluded.team,
  member_type = excluded.member_type,
  qualification = excluded.qualification,
  last_name = excluded.last_name,
  first_name = excluded.first_name,
  phone = excluded.phone,
  email = excluded.email,
  residence_address = excluded.residence_address,
  residence_zip = excluded.residence_zip,
  residence_city = excluded.residence_city,
  residence_province = excluded.residence_province,
  birth_place = excluded.birth_place,
  birth_province = excluded.birth_province,
  birth_date = excluded.birth_date,
  ansmi_card_number = excluded.ansmi_card_number,
  nv_card_number = excluded.nv_card_number,
  pc_insurance = excluded.pc_insurance;

insert into public.volunteers (
  reg_number, reg_type, entry_date, exit_date, status,
  ansmi_office, nv_office, team, member_type, qualification,
  last_name, first_name, tax_code, phone, email,
  residence_address, residence_zip, residence_city, residence_province,
  birth_place, birth_province, birth_date, ansmi_card_number, nv_card_number, pc_insurance
) values (
  '22',
  'E',
  '2022-09-03',
  NULL,
  'attivo',
  'CHIANOCCO',
  'CHIANOCCO',
  'VALSUSA',
  'S V',
  'UCRS',
  'CARDENTE',
  'EUGENIO',
  'CRDGNE47A28A222F',
  '347 0313568',
  'eugenio.card47@gmail.com',
  'VIA GARIBALDI, 25',
  '10095',
  'GRUGLIASCO',
  'TO',
  'ALPIGNANO',
  'TO',
  '1947-01-28',
  NULL,
  '036/22',
  'X'
)
on conflict (tax_code) do update set
  reg_number = excluded.reg_number,
  reg_type = excluded.reg_type,
  entry_date = excluded.entry_date,
  exit_date = excluded.exit_date,
  status = excluded.status,
  ansmi_office = excluded.ansmi_office,
  nv_office = excluded.nv_office,
  team = excluded.team,
  member_type = excluded.member_type,
  qualification = excluded.qualification,
  last_name = excluded.last_name,
  first_name = excluded.first_name,
  phone = excluded.phone,
  email = excluded.email,
  residence_address = excluded.residence_address,
  residence_zip = excluded.residence_zip,
  residence_city = excluded.residence_city,
  residence_province = excluded.residence_province,
  birth_place = excluded.birth_place,
  birth_province = excluded.birth_province,
  birth_date = excluded.birth_date,
  ansmi_card_number = excluded.ansmi_card_number,
  nv_card_number = excluded.nv_card_number,
  pc_insurance = excluded.pc_insurance;

insert into public.volunteers (
  reg_number, reg_type, entry_date, exit_date, status,
  ansmi_office, nv_office, team, member_type, qualification,
  last_name, first_name, tax_code, phone, email,
  residence_address, residence_zip, residence_city, residence_province,
  birth_place, birth_province, birth_date, ansmi_card_number, nv_card_number, pc_insurance
) values (
  '23',
  'U',
  '2023-02-22',
  '2024-11-20',
  'uscito',
  'CHIANOCCO',
  'CHIANOCCO',
  NULL,
  NULL,
  'PC',
  'AVIDANO',
  'BRUNO',
  'VDNBRN80L01L219M',
  '340 7556243',
  'avidano.bruno.ba@gmail.com',
  'VIA DEL COLLE, 5',
  '10058',
  'SESTRIERE',
  'TO',
  'TORINO',
  'TO',
  '1980-07-01',
  NULL,
  NULL,
  'X'
)
on conflict (tax_code) do update set
  reg_number = excluded.reg_number,
  reg_type = excluded.reg_type,
  entry_date = excluded.entry_date,
  exit_date = excluded.exit_date,
  status = excluded.status,
  ansmi_office = excluded.ansmi_office,
  nv_office = excluded.nv_office,
  team = excluded.team,
  member_type = excluded.member_type,
  qualification = excluded.qualification,
  last_name = excluded.last_name,
  first_name = excluded.first_name,
  phone = excluded.phone,
  email = excluded.email,
  residence_address = excluded.residence_address,
  residence_zip = excluded.residence_zip,
  residence_city = excluded.residence_city,
  residence_province = excluded.residence_province,
  birth_place = excluded.birth_place,
  birth_province = excluded.birth_province,
  birth_date = excluded.birth_date,
  ansmi_card_number = excluded.ansmi_card_number,
  nv_card_number = excluded.nv_card_number,
  pc_insurance = excluded.pc_insurance;

insert into public.volunteers (
  reg_number, reg_type, entry_date, exit_date, status,
  ansmi_office, nv_office, team, member_type, qualification,
  last_name, first_name, tax_code, phone, email,
  residence_address, residence_zip, residence_city, residence_province,
  birth_place, birth_province, birth_date, ansmi_card_number, nv_card_number, pc_insurance
) values (
  '24',
  'E',
  '2023-05-04',
  NULL,
  'attivo',
  'CHIANOCCO',
  'CHIANOCCO',
  'VALSUSA',
  'S V',
  'PC',
  'BORGARO',
  'ROBERTA',
  'BRGRRT72M47L219Q',
  '339 6087063',
  'roberta.borgaro@gmail.com',
  'VIA PLAGNOL, 8',
  '10058',
  'SESTRIERE',
  'TO',
  'TORINO',
  'TO',
  '1972-08-07',
  NULL,
  '038/23',
  'X'
)
on conflict (tax_code) do update set
  reg_number = excluded.reg_number,
  reg_type = excluded.reg_type,
  entry_date = excluded.entry_date,
  exit_date = excluded.exit_date,
  status = excluded.status,
  ansmi_office = excluded.ansmi_office,
  nv_office = excluded.nv_office,
  team = excluded.team,
  member_type = excluded.member_type,
  qualification = excluded.qualification,
  last_name = excluded.last_name,
  first_name = excluded.first_name,
  phone = excluded.phone,
  email = excluded.email,
  residence_address = excluded.residence_address,
  residence_zip = excluded.residence_zip,
  residence_city = excluded.residence_city,
  residence_province = excluded.residence_province,
  birth_place = excluded.birth_place,
  birth_province = excluded.birth_province,
  birth_date = excluded.birth_date,
  ansmi_card_number = excluded.ansmi_card_number,
  nv_card_number = excluded.nv_card_number,
  pc_insurance = excluded.pc_insurance;

insert into public.dogs (
  volunteer_id, name, breed, sex, microchip, loi_code, pedigree_name, birth_date,
  enci_booklet_number, enci_sup_license, enci_mac_license, medical_certificate, vaccinations
)
select
  v.id,
  'FURIA',
  'LUPO ITALIANO',
  'F',
  '380260102347661',
  NULL,
  'FURIA',
  '2022-05-17',
  NULL,
  NULL,
  NULL,
  NULL,
  'OK'
from public.volunteers v
where v.tax_code = 'BRGRRT72M47L219Q'
on conflict (microchip) do update set
  volunteer_id = excluded.volunteer_id,
  name = excluded.name,
  breed = excluded.breed,
  sex = excluded.sex,
  loi_code = excluded.loi_code,
  pedigree_name = excluded.pedigree_name,
  birth_date = excluded.birth_date,
  enci_booklet_number = excluded.enci_booklet_number,
  enci_sup_license = excluded.enci_sup_license,
  enci_mac_license = excluded.enci_mac_license,
  medical_certificate = excluded.medical_certificate,
  vaccinations = excluded.vaccinations;

insert into public.volunteers (
  reg_number, reg_type, entry_date, exit_date, status,
  ansmi_office, nv_office, team, member_type, qualification,
  last_name, first_name, tax_code, phone, email,
  residence_address, residence_zip, residence_city, residence_province,
  birth_place, birth_province, birth_date, ansmi_card_number, nv_card_number, pc_insurance
) values (
  '25',
  'E',
  '2023-07-16',
  NULL,
  'attivo',
  'CHIANOCCO',
  'CHIANOCCO',
  'VALSUSA',
  'S V',
  'UCRS',
  'BLANCHET',
  'CRISTINA',
  'BLNCST71A57L013V',
  '339 8570339',
  'cristina17b@gmail.com',
  'FRAZ. SAN SICARIO, 6',
  '10054',
  'CESANA T.SE',
  'TO',
  'SUSA',
  'TO',
  '1971-01-17',
  NULL,
  '040/24',
  'X'
)
on conflict (tax_code) do update set
  reg_number = excluded.reg_number,
  reg_type = excluded.reg_type,
  entry_date = excluded.entry_date,
  exit_date = excluded.exit_date,
  status = excluded.status,
  ansmi_office = excluded.ansmi_office,
  nv_office = excluded.nv_office,
  team = excluded.team,
  member_type = excluded.member_type,
  qualification = excluded.qualification,
  last_name = excluded.last_name,
  first_name = excluded.first_name,
  phone = excluded.phone,
  email = excluded.email,
  residence_address = excluded.residence_address,
  residence_zip = excluded.residence_zip,
  residence_city = excluded.residence_city,
  residence_province = excluded.residence_province,
  birth_place = excluded.birth_place,
  birth_province = excluded.birth_province,
  birth_date = excluded.birth_date,
  ansmi_card_number = excluded.ansmi_card_number,
  nv_card_number = excluded.nv_card_number,
  pc_insurance = excluded.pc_insurance;

insert into public.volunteers (
  reg_number, reg_type, entry_date, exit_date, status,
  ansmi_office, nv_office, team, member_type, qualification,
  last_name, first_name, tax_code, phone, email,
  residence_address, residence_zip, residence_city, residence_province,
  birth_place, birth_province, birth_date, ansmi_card_number, nv_card_number, pc_insurance
) values (
  '26',
  'U',
  '2024-01-22',
  '2025-02-01',
  'uscito',
  'CHIANOCCO',
  'CHIANOCCO',
  'VALSUSA',
  NULL,
  'UCRS',
  'MINATO',
  'CLARA',
  'MNTCLR97A53L219R',
  '340 2829744',
  'clara.minato97@gmail.com',
  'VIA ONORATO VIGLIANI, 164/52',
  '10127',
  'TORINO',
  'TO',
  'TORINO',
  'TO',
  '1997-01-13',
  NULL,
  NULL,
  NULL
)
on conflict (tax_code) do update set
  reg_number = excluded.reg_number,
  reg_type = excluded.reg_type,
  entry_date = excluded.entry_date,
  exit_date = excluded.exit_date,
  status = excluded.status,
  ansmi_office = excluded.ansmi_office,
  nv_office = excluded.nv_office,
  team = excluded.team,
  member_type = excluded.member_type,
  qualification = excluded.qualification,
  last_name = excluded.last_name,
  first_name = excluded.first_name,
  phone = excluded.phone,
  email = excluded.email,
  residence_address = excluded.residence_address,
  residence_zip = excluded.residence_zip,
  residence_city = excluded.residence_city,
  residence_province = excluded.residence_province,
  birth_place = excluded.birth_place,
  birth_province = excluded.birth_province,
  birth_date = excluded.birth_date,
  ansmi_card_number = excluded.ansmi_card_number,
  nv_card_number = excluded.nv_card_number,
  pc_insurance = excluded.pc_insurance;

insert into public.dogs (
  volunteer_id, name, breed, sex, microchip, loi_code, pedigree_name, birth_date,
  enci_booklet_number, enci_sup_license, enci_mac_license, medical_certificate, vaccinations
)
select
  v.id,
  'JERRY',
  'METICCIO',
  'M',
  NULL,
  NULL,
  'JERRY',
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL
from public.volunteers v
where v.tax_code = 'MNTCLR97A53L219R'
on conflict (microchip) do update set
  volunteer_id = excluded.volunteer_id,
  name = excluded.name,
  breed = excluded.breed,
  sex = excluded.sex,
  loi_code = excluded.loi_code,
  pedigree_name = excluded.pedigree_name,
  birth_date = excluded.birth_date,
  enci_booklet_number = excluded.enci_booklet_number,
  enci_sup_license = excluded.enci_sup_license,
  enci_mac_license = excluded.enci_mac_license,
  medical_certificate = excluded.medical_certificate,
  vaccinations = excluded.vaccinations;

insert into public.volunteers (
  reg_number, reg_type, entry_date, exit_date, status,
  ansmi_office, nv_office, team, member_type, qualification,
  last_name, first_name, tax_code, phone, email,
  residence_address, residence_zip, residence_city, residence_province,
  birth_place, birth_province, birth_date, ansmi_card_number, nv_card_number, pc_insurance
) values (
  '27',
  'U',
  '2025-01-14',
  '2025-01-14',
  'uscito',
  'CHIANOCCO',
  'CHIANOCCO',
  NULL,
  NULL,
  'PC',
  'VILLANI',
  'GAIA',
  'VLLGAI67E57G273O',
  '392 4214855',
  'info@gaiavillani.com',
  'VIA CADUTI DELLA LIBERTA'', 3',
  '40012',
  'CALDERARA DI RENO',
  'BO',
  'PALERMO',
  'PA',
  '1967-05-17',
  NULL,
  NULL,
  'X'
)
on conflict (tax_code) do update set
  reg_number = excluded.reg_number,
  reg_type = excluded.reg_type,
  entry_date = excluded.entry_date,
  exit_date = excluded.exit_date,
  status = excluded.status,
  ansmi_office = excluded.ansmi_office,
  nv_office = excluded.nv_office,
  team = excluded.team,
  member_type = excluded.member_type,
  qualification = excluded.qualification,
  last_name = excluded.last_name,
  first_name = excluded.first_name,
  phone = excluded.phone,
  email = excluded.email,
  residence_address = excluded.residence_address,
  residence_zip = excluded.residence_zip,
  residence_city = excluded.residence_city,
  residence_province = excluded.residence_province,
  birth_place = excluded.birth_place,
  birth_province = excluded.birth_province,
  birth_date = excluded.birth_date,
  ansmi_card_number = excluded.ansmi_card_number,
  nv_card_number = excluded.nv_card_number,
  pc_insurance = excluded.pc_insurance;

insert into public.volunteers (
  reg_number, reg_type, entry_date, exit_date, status,
  ansmi_office, nv_office, team, member_type, qualification,
  last_name, first_name, tax_code, phone, email,
  residence_address, residence_zip, residence_city, residence_province,
  birth_place, birth_province, birth_date, ansmi_card_number, nv_card_number, pc_insurance
) values (
  '28',
  'E',
  '2024-04-18',
  NULL,
  'attivo',
  'CHIANOCCO',
  'CHIANOCCO',
  'VALSUSA',
  'S V',
  'UCRS',
  'ACCICA',
  'ALBERTO',
  'CCCLRT80R01L219L',
  '348 8742199',
  'lupez80@libero.it',
  'VIA MONGINEVRO, 83',
  '10056',
  'OULX',
  'TO',
  'TORINO',
  'TO',
  '1980-10-01',
  NULL,
  '041/24',
  'X'
)
on conflict (tax_code) do update set
  reg_number = excluded.reg_number,
  reg_type = excluded.reg_type,
  entry_date = excluded.entry_date,
  exit_date = excluded.exit_date,
  status = excluded.status,
  ansmi_office = excluded.ansmi_office,
  nv_office = excluded.nv_office,
  team = excluded.team,
  member_type = excluded.member_type,
  qualification = excluded.qualification,
  last_name = excluded.last_name,
  first_name = excluded.first_name,
  phone = excluded.phone,
  email = excluded.email,
  residence_address = excluded.residence_address,
  residence_zip = excluded.residence_zip,
  residence_city = excluded.residence_city,
  residence_province = excluded.residence_province,
  birth_place = excluded.birth_place,
  birth_province = excluded.birth_province,
  birth_date = excluded.birth_date,
  ansmi_card_number = excluded.ansmi_card_number,
  nv_card_number = excluded.nv_card_number,
  pc_insurance = excluded.pc_insurance;

insert into public.dogs (
  volunteer_id, name, breed, sex, microchip, loi_code, pedigree_name, birth_date,
  enci_booklet_number, enci_sup_license, enci_mac_license, medical_certificate, vaccinations
)
select
  v.id,
  'RUFFO',
  'METICCIO',
  'M',
  NULL,
  NULL,
  'RUFFO',
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL
from public.volunteers v
where v.tax_code = 'CCCLRT80R01L219L'
on conflict (microchip) do update set
  volunteer_id = excluded.volunteer_id,
  name = excluded.name,
  breed = excluded.breed,
  sex = excluded.sex,
  loi_code = excluded.loi_code,
  pedigree_name = excluded.pedigree_name,
  birth_date = excluded.birth_date,
  enci_booklet_number = excluded.enci_booklet_number,
  enci_sup_license = excluded.enci_sup_license,
  enci_mac_license = excluded.enci_mac_license,
  medical_certificate = excluded.medical_certificate,
  vaccinations = excluded.vaccinations;

insert into public.volunteers (
  reg_number, reg_type, entry_date, exit_date, status,
  ansmi_office, nv_office, team, member_type, qualification,
  last_name, first_name, tax_code, phone, email,
  residence_address, residence_zip, residence_city, residence_province,
  birth_place, birth_province, birth_date, ansmi_card_number, nv_card_number, pc_insurance
) values (
  '29',
  'E',
  '2024-04-18',
  NULL,
  'attivo',
  'CHIANOCCO',
  'CHIANOCCO',
  'VALSUSA',
  NULL,
  'ISTR TECH',
  'SANSON',
  'MASSIMO',
  'SNSMSM63P26G284J',
  '366 6684403',
  'gasanson63@gmail.com',
  'VIA GRAVERE, 3',
  '10059',
  'SUSA',
  'TO',
  'PALMANOVA',
  'UD',
  '1963-09-26',
  NULL,
  '039/24',
  NULL
)
on conflict (tax_code) do update set
  reg_number = excluded.reg_number,
  reg_type = excluded.reg_type,
  entry_date = excluded.entry_date,
  exit_date = excluded.exit_date,
  status = excluded.status,
  ansmi_office = excluded.ansmi_office,
  nv_office = excluded.nv_office,
  team = excluded.team,
  member_type = excluded.member_type,
  qualification = excluded.qualification,
  last_name = excluded.last_name,
  first_name = excluded.first_name,
  phone = excluded.phone,
  email = excluded.email,
  residence_address = excluded.residence_address,
  residence_zip = excluded.residence_zip,
  residence_city = excluded.residence_city,
  residence_province = excluded.residence_province,
  birth_place = excluded.birth_place,
  birth_province = excluded.birth_province,
  birth_date = excluded.birth_date,
  ansmi_card_number = excluded.ansmi_card_number,
  nv_card_number = excluded.nv_card_number,
  pc_insurance = excluded.pc_insurance;

insert into public.volunteers (
  reg_number, reg_type, entry_date, exit_date, status,
  ansmi_office, nv_office, team, member_type, qualification,
  last_name, first_name, tax_code, phone, email,
  residence_address, residence_zip, residence_city, residence_province,
  birth_place, birth_province, birth_date, ansmi_card_number, nv_card_number, pc_insurance
) values (
  '30',
  'E',
  '2024-09-04',
  NULL,
  'attivo',
  'CHIANOCCO',
  'CHIANOCCO',
  'VALSUSA',
  'S V',
  'UCRS',
  'GORLIER',
  'FEDERICA',
  'GRLFRC74R57L219K',
  '349 0979249',
  'fedegorlier@gmail.com',
  'FRAZ. CHAMPLAS SEGUIN, 14',
  '10054',
  'CESANA T.SE',
  'TO',
  'TORINO',
  'TO',
  '1974-10-17',
  NULL,
  '042/24',
  'X'
)
on conflict (tax_code) do update set
  reg_number = excluded.reg_number,
  reg_type = excluded.reg_type,
  entry_date = excluded.entry_date,
  exit_date = excluded.exit_date,
  status = excluded.status,
  ansmi_office = excluded.ansmi_office,
  nv_office = excluded.nv_office,
  team = excluded.team,
  member_type = excluded.member_type,
  qualification = excluded.qualification,
  last_name = excluded.last_name,
  first_name = excluded.first_name,
  phone = excluded.phone,
  email = excluded.email,
  residence_address = excluded.residence_address,
  residence_zip = excluded.residence_zip,
  residence_city = excluded.residence_city,
  residence_province = excluded.residence_province,
  birth_place = excluded.birth_place,
  birth_province = excluded.birth_province,
  birth_date = excluded.birth_date,
  ansmi_card_number = excluded.ansmi_card_number,
  nv_card_number = excluded.nv_card_number,
  pc_insurance = excluded.pc_insurance;

insert into public.dogs (
  volunteer_id, name, breed, sex, microchip, loi_code, pedigree_name, birth_date,
  enci_booklet_number, enci_sup_license, enci_mac_license, medical_certificate, vaccinations
)
select
  v.id,
  'ZAIS GOLDEN DI CASA GORENA',
  'GOLDEN RETRIEVER',
  'M',
  '380260120023585',
  '24/54855',
  'ZAIS GOLDEN DI CASA GORENA',
  '2024-02-07',
  NULL,
  NULL,
  NULL,
  NULL,
  NULL
from public.volunteers v
where v.tax_code = 'GRLFRC74R57L219K'
on conflict (microchip) do update set
  volunteer_id = excluded.volunteer_id,
  name = excluded.name,
  breed = excluded.breed,
  sex = excluded.sex,
  loi_code = excluded.loi_code,
  pedigree_name = excluded.pedigree_name,
  birth_date = excluded.birth_date,
  enci_booklet_number = excluded.enci_booklet_number,
  enci_sup_license = excluded.enci_sup_license,
  enci_mac_license = excluded.enci_mac_license,
  medical_certificate = excluded.medical_certificate,
  vaccinations = excluded.vaccinations;

insert into public.volunteers (
  reg_number, reg_type, entry_date, exit_date, status,
  ansmi_office, nv_office, team, member_type, qualification,
  last_name, first_name, tax_code, phone, email,
  residence_address, residence_zip, residence_city, residence_province,
  birth_place, birth_province, birth_date, ansmi_card_number, nv_card_number, pc_insurance
) values (
  '31',
  'E',
  '2024-10-15',
  NULL,
  'attivo',
  'CHIANOCCO',
  'CHIANOCCO',
  'VALSUSA',
  'S V',
  'UCRS',
  'FURLAN',
  'ENRICO GIUSEPPE',
  'FRLNCG56H10L219E',
  '349 3064919',
  'enfurlan@gmail.com',
  'CORSO REGINA MARGHERITA, 288',
  '10100',
  'TORINO',
  'TO',
  'TORINO',
  'TO',
  '1956-06-10',
  NULL,
  '043/24',
  'X'
)
on conflict (tax_code) do update set
  reg_number = excluded.reg_number,
  reg_type = excluded.reg_type,
  entry_date = excluded.entry_date,
  exit_date = excluded.exit_date,
  status = excluded.status,
  ansmi_office = excluded.ansmi_office,
  nv_office = excluded.nv_office,
  team = excluded.team,
  member_type = excluded.member_type,
  qualification = excluded.qualification,
  last_name = excluded.last_name,
  first_name = excluded.first_name,
  phone = excluded.phone,
  email = excluded.email,
  residence_address = excluded.residence_address,
  residence_zip = excluded.residence_zip,
  residence_city = excluded.residence_city,
  residence_province = excluded.residence_province,
  birth_place = excluded.birth_place,
  birth_province = excluded.birth_province,
  birth_date = excluded.birth_date,
  ansmi_card_number = excluded.ansmi_card_number,
  nv_card_number = excluded.nv_card_number,
  pc_insurance = excluded.pc_insurance;

insert into public.dogs (
  volunteer_id, name, breed, sex, microchip, loi_code, pedigree_name, birth_date,
  enci_booklet_number, enci_sup_license, enci_mac_license, medical_certificate, vaccinations
)
select
  v.id,
  'GEBO',
  'METICCIO',
  'M',
  '380260120170255',
  NULL,
  'GEBO',
  '2021-03-26',
  NULL,
  NULL,
  NULL,
  NULL,
  NULL
from public.volunteers v
where v.tax_code = 'FRLNCG56H10L219E'
on conflict (microchip) do update set
  volunteer_id = excluded.volunteer_id,
  name = excluded.name,
  breed = excluded.breed,
  sex = excluded.sex,
  loi_code = excluded.loi_code,
  pedigree_name = excluded.pedigree_name,
  birth_date = excluded.birth_date,
  enci_booklet_number = excluded.enci_booklet_number,
  enci_sup_license = excluded.enci_sup_license,
  enci_mac_license = excluded.enci_mac_license,
  medical_certificate = excluded.medical_certificate,
  vaccinations = excluded.vaccinations;

insert into public.volunteers (
  reg_number, reg_type, entry_date, exit_date, status,
  ansmi_office, nv_office, team, member_type, qualification,
  last_name, first_name, tax_code, phone, email,
  residence_address, residence_zip, residence_city, residence_province,
  birth_place, birth_province, birth_date, ansmi_card_number, nv_card_number, pc_insurance
) values (
  '32',
  'U',
  '2025-02-01',
  '2025-11-30',
  'uscito',
  'CHIANOCCO',
  'CHIANOCCO',
  'VALSUSA',
  'S V',
  'UCRS',
  'FORNO',
  'ANNA MARIA',
  'FRNNMR02E58L013Y',
  '389 3108334',
  'anna.forno@icloud.com',
  'CORSO MONTENERO, 28',
  '10056',
  'OULX',
  'TO',
  'SUSA',
  'TO',
  '2002-05-18',
  NULL,
  '044/25',
  'X'
)
on conflict (tax_code) do update set
  reg_number = excluded.reg_number,
  reg_type = excluded.reg_type,
  entry_date = excluded.entry_date,
  exit_date = excluded.exit_date,
  status = excluded.status,
  ansmi_office = excluded.ansmi_office,
  nv_office = excluded.nv_office,
  team = excluded.team,
  member_type = excluded.member_type,
  qualification = excluded.qualification,
  last_name = excluded.last_name,
  first_name = excluded.first_name,
  phone = excluded.phone,
  email = excluded.email,
  residence_address = excluded.residence_address,
  residence_zip = excluded.residence_zip,
  residence_city = excluded.residence_city,
  residence_province = excluded.residence_province,
  birth_place = excluded.birth_place,
  birth_province = excluded.birth_province,
  birth_date = excluded.birth_date,
  ansmi_card_number = excluded.ansmi_card_number,
  nv_card_number = excluded.nv_card_number,
  pc_insurance = excluded.pc_insurance;

insert into public.dogs (
  volunteer_id, name, breed, sex, microchip, loi_code, pedigree_name, birth_date,
  enci_booklet_number, enci_sup_license, enci_mac_license, medical_certificate, vaccinations
)
select
  v.id,
  'QUEEN DI VILLA TESTA',
  'PASTORE TEDESCO',
  'F',
  '380260004634477',
  'L02359468',
  'QUEEN DI VILLA TESTA',
  '2023-02-12',
  NULL,
  NULL,
  NULL,
  NULL,
  'NO'
from public.volunteers v
where v.tax_code = 'FRNNMR02E58L013Y'
on conflict (microchip) do update set
  volunteer_id = excluded.volunteer_id,
  name = excluded.name,
  breed = excluded.breed,
  sex = excluded.sex,
  loi_code = excluded.loi_code,
  pedigree_name = excluded.pedigree_name,
  birth_date = excluded.birth_date,
  enci_booklet_number = excluded.enci_booklet_number,
  enci_sup_license = excluded.enci_sup_license,
  enci_mac_license = excluded.enci_mac_license,
  medical_certificate = excluded.medical_certificate,
  vaccinations = excluded.vaccinations;

insert into public.volunteers (
  reg_number, reg_type, entry_date, exit_date, status,
  ansmi_office, nv_office, team, member_type, qualification,
  last_name, first_name, tax_code, phone, email,
  residence_address, residence_zip, residence_city, residence_province,
  birth_place, birth_province, birth_date, ansmi_card_number, nv_card_number, pc_insurance
) values (
  '33',
  'E',
  '2025-04-15',
  NULL,
  'attivo',
  'VERRUA',
  'CHIANOCCO',
  'VALSUSA',
  'S V',
  'PC',
  'VALLONE',
  'ELEONORA',
  'VLLLNR89S44A479H',
  '329 7039184',
  'vele1989@libero.it',
  'CASE VALLONE, 5',
  '15020',
  'VILLADEATI',
  'AL',
  'ASTI',
  'AT',
  '1989-11-04',
  NULL,
  '045/25',
  'X'
)
on conflict (tax_code) do update set
  reg_number = excluded.reg_number,
  reg_type = excluded.reg_type,
  entry_date = excluded.entry_date,
  exit_date = excluded.exit_date,
  status = excluded.status,
  ansmi_office = excluded.ansmi_office,
  nv_office = excluded.nv_office,
  team = excluded.team,
  member_type = excluded.member_type,
  qualification = excluded.qualification,
  last_name = excluded.last_name,
  first_name = excluded.first_name,
  phone = excluded.phone,
  email = excluded.email,
  residence_address = excluded.residence_address,
  residence_zip = excluded.residence_zip,
  residence_city = excluded.residence_city,
  residence_province = excluded.residence_province,
  birth_place = excluded.birth_place,
  birth_province = excluded.birth_province,
  birth_date = excluded.birth_date,
  ansmi_card_number = excluded.ansmi_card_number,
  nv_card_number = excluded.nv_card_number,
  pc_insurance = excluded.pc_insurance;

insert into public.volunteers (
  reg_number, reg_type, entry_date, exit_date, status,
  ansmi_office, nv_office, team, member_type, qualification,
  last_name, first_name, tax_code, phone, email,
  residence_address, residence_zip, residence_city, residence_province,
  birth_place, birth_province, birth_date, ansmi_card_number, nv_card_number, pc_insurance
) values (
  '34',
  'E',
  '2025-07-08',
  NULL,
  'attivo',
  'CHIANOCCO',
  'CHIANOCCO',
  'VALSUSA',
  'S V',
  'PC',
  'CAVAZZINI',
  'LUCA',
  'CVZLCU76L26E020H',
  '338 2399928',
  'cavazzini.luca1976@gmail.com',
  'VIA MANTEGNA, 2',
  '10045',
  'PIOSSASCO',
  'TO',
  'GIAVENO',
  'TO',
  '1976-07-26',
  NULL,
  '046/25',
  'X'
)
on conflict (tax_code) do update set
  reg_number = excluded.reg_number,
  reg_type = excluded.reg_type,
  entry_date = excluded.entry_date,
  exit_date = excluded.exit_date,
  status = excluded.status,
  ansmi_office = excluded.ansmi_office,
  nv_office = excluded.nv_office,
  team = excluded.team,
  member_type = excluded.member_type,
  qualification = excluded.qualification,
  last_name = excluded.last_name,
  first_name = excluded.first_name,
  phone = excluded.phone,
  email = excluded.email,
  residence_address = excluded.residence_address,
  residence_zip = excluded.residence_zip,
  residence_city = excluded.residence_city,
  residence_province = excluded.residence_province,
  birth_place = excluded.birth_place,
  birth_province = excluded.birth_province,
  birth_date = excluded.birth_date,
  ansmi_card_number = excluded.ansmi_card_number,
  nv_card_number = excluded.nv_card_number,
  pc_insurance = excluded.pc_insurance;

insert into public.volunteers (
  reg_number, reg_type, entry_date, exit_date, status,
  ansmi_office, nv_office, team, member_type, qualification,
  last_name, first_name, tax_code, phone, email,
  residence_address, residence_zip, residence_city, residence_province,
  birth_place, birth_province, birth_date, ansmi_card_number, nv_card_number, pc_insurance
) values (
  '35',
  'E',
  '2025-08-01',
  NULL,
  'attivo',
  'CHIANOCCO',
  'CHIANOCCO',
  'VALSUSA',
  'S V',
  'UCRS',
  'LORENZALE',
  'CARLO',
  'LRNCRL99B19L219W',
  '392 2816188',
  'lorenzalecarlo1@gmail.com',
  'VIA ROMA, 25',
  '10054',
  'CESANA TORINESE',
  'TO',
  'TORINO',
  'TO',
  '1999-02-19',
  NULL,
  '047/25',
  'X'
)
on conflict (tax_code) do update set
  reg_number = excluded.reg_number,
  reg_type = excluded.reg_type,
  entry_date = excluded.entry_date,
  exit_date = excluded.exit_date,
  status = excluded.status,
  ansmi_office = excluded.ansmi_office,
  nv_office = excluded.nv_office,
  team = excluded.team,
  member_type = excluded.member_type,
  qualification = excluded.qualification,
  last_name = excluded.last_name,
  first_name = excluded.first_name,
  phone = excluded.phone,
  email = excluded.email,
  residence_address = excluded.residence_address,
  residence_zip = excluded.residence_zip,
  residence_city = excluded.residence_city,
  residence_province = excluded.residence_province,
  birth_place = excluded.birth_place,
  birth_province = excluded.birth_province,
  birth_date = excluded.birth_date,
  ansmi_card_number = excluded.ansmi_card_number,
  nv_card_number = excluded.nv_card_number,
  pc_insurance = excluded.pc_insurance;

insert into public.volunteers (
  reg_number, reg_type, entry_date, exit_date, status,
  ansmi_office, nv_office, team, member_type, qualification,
  last_name, first_name, tax_code, phone, email,
  residence_address, residence_zip, residence_city, residence_province,
  birth_place, birth_province, birth_date, ansmi_card_number, nv_card_number, pc_insurance
) values (
  '36',
  'E',
  '2025-08-01',
  NULL,
  'attivo',
  'CHIANOCCO',
  'CHIANOCCO',
  'VALSUSA',
  'S V',
  'UCRS',
  'ZANELLATO',
  'IRENE',
  'ZNLRNI00H45L219C',
  '351 7632111',
  'irezanellato@gmail.com',
  'VIA ROMA, 25',
  '10054',
  'CESANA TORINESE',
  'TO',
  'TORINO',
  'TO',
  '2000-06-05',
  NULL,
  '048/25',
  'X'
)
on conflict (tax_code) do update set
  reg_number = excluded.reg_number,
  reg_type = excluded.reg_type,
  entry_date = excluded.entry_date,
  exit_date = excluded.exit_date,
  status = excluded.status,
  ansmi_office = excluded.ansmi_office,
  nv_office = excluded.nv_office,
  team = excluded.team,
  member_type = excluded.member_type,
  qualification = excluded.qualification,
  last_name = excluded.last_name,
  first_name = excluded.first_name,
  phone = excluded.phone,
  email = excluded.email,
  residence_address = excluded.residence_address,
  residence_zip = excluded.residence_zip,
  residence_city = excluded.residence_city,
  residence_province = excluded.residence_province,
  birth_place = excluded.birth_place,
  birth_province = excluded.birth_province,
  birth_date = excluded.birth_date,
  ansmi_card_number = excluded.ansmi_card_number,
  nv_card_number = excluded.nv_card_number,
  pc_insurance = excluded.pc_insurance;

insert into public.volunteers (
  reg_number, reg_type, entry_date, exit_date, status,
  ansmi_office, nv_office, team, member_type, qualification,
  last_name, first_name, tax_code, phone, email,
  residence_address, residence_zip, residence_city, residence_province,
  birth_place, birth_province, birth_date, ansmi_card_number, nv_card_number, pc_insurance
) values (
  '37',
  'E',
  NULL,
  NULL,
  'attivo',
  'CHIANOCCO',
  'CHIANOCCO',
  'VALSUSA',
  'S V',
  'UCRS',
  'MALETTO',
  'DANIELE',
  'MLTDNL76E03L219Y',
  '375 9017741',
  'nama2015@libero.it',
  'VIA ROCCIAMELONE, 13',
  '10090',
  'VILLARBASSE',
  'TO',
  'TORINO',
  'TO',
  '1976-05-03',
  NULL,
  '049/25',
  NULL
)
on conflict (tax_code) do update set
  reg_number = excluded.reg_number,
  reg_type = excluded.reg_type,
  entry_date = excluded.entry_date,
  exit_date = excluded.exit_date,
  status = excluded.status,
  ansmi_office = excluded.ansmi_office,
  nv_office = excluded.nv_office,
  team = excluded.team,
  member_type = excluded.member_type,
  qualification = excluded.qualification,
  last_name = excluded.last_name,
  first_name = excluded.first_name,
  phone = excluded.phone,
  email = excluded.email,
  residence_address = excluded.residence_address,
  residence_zip = excluded.residence_zip,
  residence_city = excluded.residence_city,
  residence_province = excluded.residence_province,
  birth_place = excluded.birth_place,
  birth_province = excluded.birth_province,
  birth_date = excluded.birth_date,
  ansmi_card_number = excluded.ansmi_card_number,
  nv_card_number = excluded.nv_card_number,
  pc_insurance = excluded.pc_insurance;

insert into public.volunteers (
  reg_number, reg_type, entry_date, exit_date, status,
  ansmi_office, nv_office, team, member_type, qualification,
  last_name, first_name, tax_code, phone, email,
  residence_address, residence_zip, residence_city, residence_province,
  birth_place, birth_province, birth_date, ansmi_card_number, nv_card_number, pc_insurance
) values (
  '38',
  'E',
  '2026-03-01',
  '2026-03-01',
  'attivo',
  'CHIANOCCO',
  'CHIANOCCO',
  'VALSUSA',
  'S V',
  'UCRS',
  'FERRUA',
  'ALESSANDRA',
  'FRRLSN73E63L219Y',
  '347 7854253',
  'alessandra.ferrua@gmail.com',
  'BORGATA NICOLINA, 19',
  '10040',
  'RUBIANA',
  'TO',
  'TORINO',
  'TO',
  '1973-05-23',
  NULL,
  '050/25',
  NULL
)
on conflict (tax_code) do update set
  reg_number = excluded.reg_number,
  reg_type = excluded.reg_type,
  entry_date = excluded.entry_date,
  exit_date = excluded.exit_date,
  status = excluded.status,
  ansmi_office = excluded.ansmi_office,
  nv_office = excluded.nv_office,
  team = excluded.team,
  member_type = excluded.member_type,
  qualification = excluded.qualification,
  last_name = excluded.last_name,
  first_name = excluded.first_name,
  phone = excluded.phone,
  email = excluded.email,
  residence_address = excluded.residence_address,
  residence_zip = excluded.residence_zip,
  residence_city = excluded.residence_city,
  residence_province = excluded.residence_province,
  birth_place = excluded.birth_place,
  birth_province = excluded.birth_province,
  birth_date = excluded.birth_date,
  ansmi_card_number = excluded.ansmi_card_number,
  nv_card_number = excluded.nv_card_number,
  pc_insurance = excluded.pc_insurance;

insert into public.volunteers (
  reg_number, reg_type, entry_date, exit_date, status,
  ansmi_office, nv_office, team, member_type, qualification,
  last_name, first_name, tax_code, phone, email,
  residence_address, residence_zip, residence_city, residence_province,
  birth_place, birth_province, birth_date, ansmi_card_number, nv_card_number, pc_insurance
) values (
  '39',
  'E',
  '2026-02-01',
  NULL,
  'attivo',
  'CHIANOCCO',
  'CHIANOCCO',
  'VALSUSA',
  'S V',
  'UCRS',
  'DI PONZIANO',
  'LUCA',
  'DPNLCU87S18L219S',
  '351 7789490',
  'l.diponziano@gmail.com',
  'VIA ALLIAUD, 26',
  '10054',
  'CESANA TORINESE',
  'TO',
  'TORINO',
  'TO',
  '1987-11-18',
  NULL,
  NULL,
  NULL
)
on conflict (tax_code) do update set
  reg_number = excluded.reg_number,
  reg_type = excluded.reg_type,
  entry_date = excluded.entry_date,
  exit_date = excluded.exit_date,
  status = excluded.status,
  ansmi_office = excluded.ansmi_office,
  nv_office = excluded.nv_office,
  team = excluded.team,
  member_type = excluded.member_type,
  qualification = excluded.qualification,
  last_name = excluded.last_name,
  first_name = excluded.first_name,
  phone = excluded.phone,
  email = excluded.email,
  residence_address = excluded.residence_address,
  residence_zip = excluded.residence_zip,
  residence_city = excluded.residence_city,
  residence_province = excluded.residence_province,
  birth_place = excluded.birth_place,
  birth_province = excluded.birth_province,
  birth_date = excluded.birth_date,
  ansmi_card_number = excluded.ansmi_card_number,
  nv_card_number = excluded.nv_card_number,
  pc_insurance = excluded.pc_insurance;
commit;
-- Volunteers processed: 39
-- Dogs processed: 15
